# Generated by Django 2.0.9 on 2019-07-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.IntegerField(blank=True, null=True)),
                ('partial', models.IntegerField(blank=True, null=True)),
                ('dh_key', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.IntegerField(default=19)),
                ('private_key', models.IntegerField(default=17)),
                ('dh_key', models.IntegerField(blank=True, null=True)),
                ('partial', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
