# Generated by Django 2.0.9 on 2019-07-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='local.Transactions'),
        ),
    ]
