# Generated by Django 2.0.9 on 2019-07-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_auto_20190723_0424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'get_latest_by': '-transaction_number'},
        ),
        migrations.AddField(
            model_name='transactions',
            name='device_status',
            field=models.BooleanField(default=False),
        ),
    ]
