# Generated by Django 2.0.9 on 2019-07-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0004_auto_20190723_0520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'get_latest_by': 'transaction_number'},
        ),
        migrations.AddField(
            model_name='transactions',
            name='block_transaction_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
