# Generated by Django 2.0.9 on 2019-07-23 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0005_auto_20190723_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='prev_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='local.Transactions'),
        ),
    ]
