# Generated by Django 2.0.9 on 2019-07-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0006_auto_20190723_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='block_transaction_number',
            field=models.IntegerField(),
        ),
    ]
