# Generated by Django 2.0.9 on 2019-07-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0007_auto_20190723_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='block_transaction_number',
        ),
    ]
