# Generated by Django 2.0.9 on 2019-07-23 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0008_remove_transactions_block_transaction_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='prev_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='local.Block'),
        ),
    ]
