# Generated by Django 2.2.3 on 2019-07-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0002_self_partial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.IntegerField(default=7919)),
                ('df_key', models.IntegerField(blank=True, null=True)),
                ('partial', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
