# Generated by Django 2.2.3 on 2019-07-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0003_miner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miner',
            name='public_key',
            field=models.IntegerField(default=19),
        ),
    ]
