# Generated by Django 2.2.3 on 2019-07-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0004_auto_20190722_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miner',
            old_name='df_key',
            new_name='dh_key',
        ),
        migrations.RenameField(
            model_name='self',
            old_name='df_key',
            new_name='dh_key',
        ),
    ]
