# Generated by Django 2.2.3 on 2019-07-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0005_auto_20190722_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100)),
            ],
        ),
    ]
