# Generated by Django 2.2.3 on 2019-07-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0006_globalchain'),
    ]

    operations = [
        migrations.CreateModel(
            name='hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='globalchain',
            name='hash',
        ),
        migrations.AddField(
            model_name='globalchain',
            name='hashchain',
            field=models.ManyToManyField(blank=True, to='cripto.hash'),
        ),
    ]
