# Generated by Django 2.2.3 on 2019-07-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0007_auto_20190723_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalchain',
            name='hashchain',
            field=models.ManyToManyField(blank=True, to='cripto.Hash'),
        ),
    ]
